### ISSUE TITLE
CORS OPTIONS request rejected

### ISSUE THREAD

**Issue by almereyda** [allmende/docker-matrix#15]
When using `https://riot.allmende.io` with Rambox, the browser console issues repeating errors about

```
bundle.js:23 OPTIONS https://matrix.allmende.io/_matrix/client/r0/sync?filter=41&timeout=30000&since=s9055732_123868661_1049800_8002200_662241_1373_200549_777591_79 502

/#/room/#libre.sh:matrix.allmende.io/$1559035725442wRjzV:hackerspaces.be:1 Failed to load https://matrix.allmende.io/_matrix/client/r0/sync?filter=41&timeout=30000&since=s9055732_123868661_1049800_8002200_662241_1373_200549_777591_79: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://riot.allmende.io' is therefore not allowed access.
bundle.js:41 /sync error Error: CORS request rejected: https://matrix.allmende.io/_matrix/client/r0/sync?filter=41&timeout=30000&since=s9055732_123868661_1049800_8002200_662241_1373_200549_777591_79
    at c (https://riot.allmende.io/bundles/498db95e44f3e6e5056f/bundle.js:23:55883)
    at XMLHttpRequest.o.onreadystatechange (https://riot.allmende.io/bundles/498db95e44f3e6e5056f/bundle.js:23:55409)

bundle.js:41 Error: CORS request rejected: https://matrix.allmende.io/_matrix/client/r0/sync?filter=41&timeout=30000&since=s9055732_123868661_1049800_8002200_662241_1373_200549_777591_79
    at c (bundle.js:23)
    at XMLHttpRequest.o.onreadystatechange (bundle.js:23)
```

Plus also

```
bundle.js:23 OPTIONS https://matrix.allmende.io/_matrix/client/r0/joined_groups 502

/#/room/#libre.sh:matrix.allmende.io/$1559035725442wRjzV:hackerspaces.be:1 Failed to load https://matrix.allmende.io/_matrix/client/r0/joined_groups: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://riot.allmende.io' is therefore not allowed access.
```

```
GET https://matrix.allmende.io/_matrix/client/versions 502

/#/room/#libre.sh:matrix.allmende.io/$1559035725442wRjzV:hackerspaces.be:1 Failed to load https://matrix.allmende.io/_matrix/client/versions: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://riot.allmende.io' is therefore not allowed access. The response had HTTP status code 502.
```

Including what we know from #14, we need to review the CORS settings and apply suitable patches. There is a lenghty discussion about how to do this in our current environment at https://github.com/jwilder/nginx-proxy/issues/804

**Comment by jesushfloresn** [comment]
hola, lo pudiste resolver?
