### ISSUE TITLE
CSRF protection blocks Vector's URL previews

### ISSUE THREAD

**Issue by almereyda** [allmende/docker-matrix#5]
```
ailed to load resource: the server responded with a status of 404 ()
/#/room/!JZHnXcPDYRoiDcrMxW:matrix.allmende.io:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fww…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/!JZHnXcPDYRoiDcrMxW:matrix.allmende.io:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/!JZHnXcPDYRoiDcrMxW:matrix.allmende.io:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
LinkPreviewWidget.js:58 Failed to get preview for http://www.spiegel.de/fotostrecke/seebaer-schwandt-navigation-ist-wenn-man-trotzdem-ankommt-fotostrecke-137508-11.html Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fww…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://archive.org/details/DubSituation Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for http://jon.patterns.wiki.transformap.co/view/welcome-visitors/view/resource…-first/ward.fed.wiki.org/predicted-results/ward.fed.wiki.org/welcome-pages Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo

Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fw…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fpa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fpa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
LinkPreviewWidget.js:58 Failed to get preview for https://www.jacobinmag.com/2014/06/no-shortcuts/ Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fw…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for http://jon.patterns.wiki.transformap.co/view/welcome-visitors/view/german-x…n-community/community.sfw.c2.com/developing-ideas-using-community-dialogue Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://tree.taiga.io/project/gandhiano-degrowth-2016/us/27 Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for http://patterns.wiki.transformap.co/view/welcome-visitors/jon.patterns.wiki…rs/frances.uk.fedwikihappening.net/hospitality-and-hostility-to-technology Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fpa…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://github.com/gandhiano/technology-degrowth/issues/7 Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fd…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fd…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
LinkPreviewWidget.js:58 Failed to get preview for https://drive.google.com/file/d/0B0UXRV0dOOgaUElaeWo2QXdxS2c/view Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fd…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://twitter.com/lechatpito/status/434770786348322816 Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://twitter.com/fedwiki/status/732155523823456256 Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Ft…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
LinkPreviewWidget.js:58 Failed to get preview for https://github.com/gandhiano/technology-degrowth Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=https%3A%2F%2Fg…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
https://vector.allmende.io/version?ts=1464814491222 Failed to load resource: the server responded with a status of 404 ()
https://matrix.allmende.io/_matrix/client/r0/sync?filter=3&timeout=30000&si…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: net::ERR_NETWORK_CHANGED
sync.js:561 /sync error Error: CORS request rejected: https://matrix.allmende.io/_matrix/client/r0/sync?filter=3&timeout=30000&si…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo
    at i (https://vector.allmende.io/bundle.js:77:12581)
    at XMLHttpRequest.r (https://vector.allmende.io/bundle.js:77:12391)(anonymous function) @ sync.js:561
sync.js:562Error: CORS request rejected: https://matrix.allmende.io/_matrix/client/r0/sync?filter=3&timeout=30000&si…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(…)

https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
LinkPreviewWidget.js:58Failed to get preview for http://jon.patterns.wiki.transformap.co/view/welcome-visitors/view/resource…-first/ward.fed.wiki.org/predicted-results/ward.fed.wiki.org/welcome-pages Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo(anonymous function) @ LinkPreviewWidget.js:58
https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo Failed to load resource: the server responded with a status of 404 ()
/#/room/#federation:matrix.org:1 XMLHttpRequest cannot load https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://vector.allmende.io' is therefore not allowed access. The response had HTTP status code 404.
LinkPreviewWidget.js:58Failed to get preview for http://jon.patterns.wiki.transformap.co/view/welcome-visitors/view/resource…-first/ward.fed.wiki.org/predicted-results/ward.fed.wiki.org/welcome-pages Error: CORS request rejected: https://matrix.allmende.io/_matrix/media/r0/preview_url?url=http%3A%2F%2Fjo…TE3MTA5MDUKMDAyZnNpZ25hdHVyZSArZ8VVU2Z6ET8xP2wvzvH59DEZRfgG0XbDRP0VJVCX9wo
```

**Comment by almereyda** [comment]
This was due to a configuration error. See https://github.com/matrix-org/synapse/issues/1841#issuecomment-309307172
